version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
          name: キャッシュディレクトリの所有者を変更
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "app/requirements.txt" }}
      - run:
          name: 依存関係のインストール
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r app/requirements.txt
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "app/requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: テストを実行
          command: |
            . venv/bin/activate
            cd app
            python3 manage.py test